---
# This tasks ensures the directory existance and registers the result essential for idempotence test
- name: "check if dir exists or not"
  stat:
    path: "{{ path }}"
  register: dir_check
  when: check == "ensure_dir"

# Check if directory is created
# This task creates the directory
- name: Ensures dir exists
  file:
    path: "{{ path }}"
    recurse: yes
    mode: '0755'
    state: directory
  when: check == "ensure_dir" and (not dir_check.stat.exists)
  

